version: '3.6'

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
  database:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
