version: '3.3'

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    command: "sh /run.sh"
    volumes:
      - ./:/usr/src/app
      - ./run.sh:/run.sh
  database:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_DEFAULT_PORT}
    volumes:
      - ./postgres:/var/lib/postgresql